// Miroir : la banque de questions. Chacune a deux pôles (l à gauche, r à droite) ; chacun place la barre
// pour soi, puis là où il pense que chaque autre l'a mise. Reste côté serveur : la page ne reçoit que
// les 25 questions tirées pour sa partie.
export const CATS = [
  { id: 'politique', nom: 'Politique' },
  { id: 'gouts', nom: 'Goûts' },
  { id: 'habitudes', nom: 'Habitudes' },
  { id: 'reactions', nom: 'Réactions' },
  { id: 'caractere', nom: 'Caractère' },
  { id: 'relations', nom: 'Amis et amours' },
  { id: 'vie', nom: 'Rêves et valeurs' },
];

const B = (c, list) => list.map(([q, l, r]) => ({ c, q, l, r }));

export const BANQUE = [
  ...B('politique', [
    ['L’économie, qui doit tenir la barre ?', 'L’État', 'Le marché'],
    ['Les impôts des plus riches', 'À baisser', 'À augmenter'],
    ['L’immigration', 'Plus ouverte', 'Plus contrôlée'],
    ['S’il faut choisir : l’écologie ou le pouvoir d’achat ?', 'L’écologie', 'Le pouvoir d’achat'],
    ['Le nucléaire', 'On en sort', 'On en construit'],
    ['La police devrait avoir plus de moyens.', 'Pas d’accord', 'D’accord'],
    ['Voter devrait être obligatoire.', 'Pas d’accord', 'D’accord'],
    ['L’Europe', 'Moins d’Europe', 'Plus d’Europe'],
    ['Le cannabis', 'Interdit', 'Légalisé'],
    ['Le revenu universel', 'Mauvaise idée', 'Bonne idée'],
    ['L’âge de la retraite', 'À baisser', 'À relever'],
    ['Les grandes fortunes sont méritées.', 'Pas d’accord', 'D’accord'],
    ['Les traditions', 'À faire évoluer', 'À préserver'],
    ['La politique, dans ta vie', 'Je m’en fiche', 'Ça me passionne'],
    ['Les grèves', 'Elles m’agacent', 'Je les soutiens'],
    ['La viande devrait coûter plus cher, pour la planète.', 'Pas d’accord', 'D’accord'],
    ['S’il fallait te ranger : gauche ou droite ?', 'Gauche', 'Droite'],
    ['Les réseaux sociaux interdits avant 15 ans', 'Mauvaise idée', 'Bonne idée'],
    ['La prison, c’est d’abord pour…', 'Réinsérer', 'Punir'],
    ['Les services publics', 'Plus de privé', 'Plus de public'],
  ]),
  ...B('gouts', [
    ['Thé ou café ?', 'Thé', 'Café'],
    ['Mer ou montagne ?', 'Mer', 'Montagne'],
    ['Sucré ou salé ?', 'Sucré', 'Salé'],
    ['Ville ou campagne ?', 'Ville', 'Campagne'],
    ['Chat ou chien ?', 'Chat', 'Chien'],
    ['Été ou hiver ?', 'Été', 'Hiver'],
    ['Les films d’horreur', 'Je fuis', 'J’adore'],
    ['Un livre ou une série ?', 'Un livre', 'Une série'],
    ['L’ananas sur la pizza', 'Un crime', 'Un délice'],
    ['Les vacances idéales', 'Transat et farniente', 'Sac à dos et aventure'],
    ['La musique en voiture', 'Tout doux', 'À fond'],
    ['Le fromage qui sent fort', 'Pitié', 'Plus il sent, mieux c’est'],
    ['La cuisine épicée', 'Pas pour moi', 'Plus ça pique, mieux c’est'],
    ['Un dîner chic ou un kebab à 2 h du matin ?', 'Le dîner chic', 'Le kebab'],
    ['Les comédies musicales', 'Insupportables', 'J’adore'],
    ['Un concert ou une soirée canapé ?', 'Le concert', 'Le canapé'],
    ['Le sport à la télé', 'Ennui total', 'Je ne rate rien'],
    ['Les jeux de société', 'Bof', 'Passion'],
    ['Les sushis', 'Non merci', 'Tous les jours'],
    ['La déco', 'Minimaliste', 'Plein de bibelots'],
  ]),
  ...B('habitudes', [
    ['Lève-tôt ou couche-tard ?', 'Lève-tôt', 'Couche-tard'],
    ['Ta chambre', 'Rangée au cordeau', 'Chaos organisé'],
    ['Le réveil sonne', 'Debout tout de suite', 'Cinq fois « encore cinq minutes »'],
    ['Les messages', 'Réponse dans la minute', 'Réponse trois jours plus tard'],
    ['À un rendez-vous', 'Toujours en avance', 'Toujours en retard'],
    ['Les courses', 'Liste précise', 'Au feeling'],
    ['Le téléphone', 'Rarement dans la main', 'Greffé à la main'],
    ['Le sport', 'Jamais', 'Tous les jours'],
    ['Les vacances', 'Tout est planifié', 'Sur un coup de tête'],
    ['La douche', 'Express', 'Concert de trente minutes'],
    ['Les notifications', 'Toutes coupées', 'Des centaines non lues'],
    ['Les plantes vertes', 'Je les tue toutes', 'Une jungle chez moi'],
    ['Faire la cuisine', 'Jamais', 'Tous les soirs'],
    ['Le budget', 'Chaque euro compté', 'Toujours à découvert'],
    ['Les séries', 'Un épisode à la fois', 'Une saison en une nuit'],
    ['La valise', 'La veille à minuit', 'Une semaine avant'],
    ['Les mails', 'Boîte vide', 'Douze mille non lus'],
    ['Les selfies', 'Jamais', 'Tout le temps'],
    ['Dormir', 'Six heures suffisent', 'Dix heures minimum'],
    ['Les papiers administratifs', 'Faits le jour même', 'Dans un tiroir depuis 2019'],
  ]),
  ...B('reactions', [
    ['Le serveur se trompe dans ta commande', 'Tu manges sans rien dire', 'Tu le fais remarquer'],
    ['Une araignée dans la chambre', 'Tu la sors délicatement', 'Tu dors ailleurs'],
    ['Tu gagnes 10 000 € demain', 'Tout de côté', 'Tout dépensé dans le mois'],
    ['Un ami te montre sa coupe ratée', 'Tu mens gentiment', 'Tu dis la vérité'],
    ['Un inconnu te parle dans le train', 'Écouteurs, vite', 'Grande discussion'],
    ['On te fait une fête surprise', 'Gêne absolue', 'Bonheur total'],
    ['Tu te perds en voiture', 'Tu demandes ton chemin', 'Tu tournes une heure plutôt que d’avouer'],
    ['Une dispute éclate dans le groupe de discussion', 'Tu lis en silence', 'Tu donnes ton avis'],
    ['Un plat inconnu sur la carte', 'Tu prends ce que tu connais', 'Tu tentes le plus bizarre'],
    ['On te critique devant tout le monde', 'Tu encaisses', 'Tu réponds du tac au tac'],
    ['Une soirée karaoké', 'Spectateur', 'Micro en main toute la nuit'],
    ['Un jeu de société tourne à ton désavantage', 'Tu laisses gagner', 'Tu veux gagner coûte que coûte'],
    ['Le film est nul au cinéma', 'Tu restes jusqu’au bout', 'Tu sors au bout de vingt minutes'],
    ['Ta soirée est annulée au dernier moment', 'Soulagement', 'Grosse déception'],
    ['Panne de courant un soir', 'Bougies et jeux de cartes', 'Panique, plus de batterie'],
    ['Il reste une part de gâteau', 'Tu la proposes aux autres', 'Elle est déjà dans ta bouche'],
    ['Tu reçois un cadeau moche', 'Tu fais semblant d’adorer', 'Ça se lit sur ton visage'],
    ['Deux amis se disputent devant toi', 'Tu calmes tout le monde', 'Tu prends parti'],
    ['Tu casses un objet chez quelqu’un', 'Tu l’avoues tout de suite', 'Tu caches les morceaux'],
    ['Quelqu’un te double dans la file', 'Tu laisses passer', 'Tu le fais remarquer'],
  ]),
  ...B('caractere', [
    ['En soirée', 'Discret', 'Le centre de l’attention'],
    ['Les décisions', 'Longuement réfléchies', 'Prises sur un coup de tête'],
    ['Les rancunes', 'Vite oubliées', 'Jamais oubliées'],
    ['La patience', 'Aucune', 'Infinie'],
    ['Plutôt optimiste ou pessimiste ?', 'Pessimiste', 'Optimiste'],
    ['Changer d’avis', 'Facilement', 'Jamais de la vie'],
    ['Le stress', 'Zen en toutes circonstances', 'Stressé pour un rien'],
    ['Les compliments', 'Gêné de les recevoir', 'Tu adores ça'],
    ['Perdre à un jeu', 'Aucune importance', 'Très mauvais perdant'],
    ['Les émotions', 'Tout reste à l’intérieur', 'Tout se lit sur ton visage'],
    ['Le risque', 'Prudence d’abord', 'Tête la première'],
    ['Être seul', 'Ça te pèse', 'Tu adores'],
    ['L’humour', 'Pince-sans-rire', 'Tu ris de tout'],
    ['Les règles', 'À respecter', 'À contourner'],
    ['La jalousie', 'Pas du tout jaloux', 'Très jaloux'],
    ['L’organisation', 'Au jour le jour', 'Un tableau pour tout'],
    ['La curiosité', 'Peu curieux', 'Tu veux tout savoir'],
    ['Les conflits', 'Tu les évites', 'Tu fonces dedans'],
    ['La franchise', 'Diplomate', 'Cash'],
    ['Le changement', 'Tu détestes', 'Tu adores'],
  ]),
  ...B('relations', [
    ['Le premier pas', 'Tu attends', 'Tu le fais'],
    ['Les déclarations', 'Discrètes', 'Spectaculaires'],
    ['Le week-end idéal', 'En tête-à-tête', 'Avec plein d’amis'],
    ['Les amis', 'Quelques-uns, très proches', 'Une grande bande'],
    ['Regarder le téléphone de l’autre', 'Jamais', 'Ça peut arriver'],
    ['Dire « je t’aime »', 'Rarement', 'Plusieurs fois par jour'],
    ['Les ex', 'On reste amis', 'Plus jamais'],
    ['Garder un secret', 'Coffre-fort', 'Tu craques vite'],
    ['Ton rôle dans le groupe', 'Celui qui écoute', 'Celui qui organise'],
    ['Les anniversaires des autres', 'Toujours oubliés', 'Jamais oubliés'],
    ['Un ami te doit de l’argent', 'Tu laisses tomber', 'Tu relances'],
    ['Le coup de foudre', 'Ça n’existe pas', 'Tu y crois'],
    ['Les câlins', 'Pas trop', 'À volonté'],
    ['Prêter tes affaires', 'Jamais', 'Sans souci'],
    ['Demander pardon', 'Très difficile', 'Facile'],
    ['Les surprises pour l’autre', 'Rarement', 'Tout le temps'],
    ['Partager ton assiette', 'Hors de question', 'Bien sûr'],
    ['La colocation', 'L’enfer', 'Le rêve'],
    ['Les mariages', 'Une corvée', 'La fête préférée'],
    ['Les messages vocaux', 'Insupportables', 'Tu en envoies de cinq minutes'],
  ]),
  ...B('vie', [
    ['L’argent', 'Pas important', 'Très important'],
    ['La carrière', 'Secondaire', 'Prioritaire'],
    ['Vivre à l’étranger', 'Jamais', 'Dès demain'],
    ['Les enfants', 'Pas pour moi', 'Une grande famille'],
    ['La célébrité', 'Un cauchemar', 'Un rêve'],
    ['Le luxe', 'Inutile', 'Indispensable'],
    ['Le destin', 'On fait sa vie', 'Tout est écrit'],
    ['La religion, dans ta vie', 'Absente', 'Centrale'],
    ['Travailler moins, gagner moins', 'Non merci', 'Tout de suite'],
    ['Tout plaquer pour élever des chèvres', 'Jamais', 'Bientôt'],
    ['La vérité, même si elle blesse', 'Pas toujours', 'Toujours'],
    ['Vivre jusqu’à 150 ans', 'Non merci', 'Avec plaisir'],
    ['La réussite, c’est surtout de la chance.', 'Pas d’accord', 'D’accord'],
    ['La maison de rêve', 'Petit appartement en ville', 'Grande maison isolée'],
    ['Le tour du monde', 'Pas pour moi', 'Le rêve'],
    ['Le passé', 'Tourné vers l’avenir', 'C’était mieux avant'],
    ['L’astrologie', 'Absurde', 'Ça explique tout'],
    ['Les amitiés', 'Elles vont et viennent', 'Pour la vie'],
    ['Le travail idéal', 'Stable et tranquille', 'Passionnant et risqué'],
    ['Laisser une trace', 'Peu importe', 'Essentiel'],
  ]),
];

/** 25 questions tirées des thèmes choisis, réparties au mieux entre eux. */
export function tirage(cats, n = 25) {
  const ids = CATS.map(c => c.id).filter(id => !cats?.length || cats.includes(id));
  const piles = ids.map(id => BANQUE.filter(q => q.c === id).sort(() => Math.random() - 0.5));
  const out = [];
  while (out.length < n && piles.some(p => p.length)) for (const p of piles) if (p.length && out.length < n) out.push(p.pop());
  return out.sort(() => Math.random() - 0.5).map(q => ({ ...q, cn: CATS.find(c => c.id === q.c).nom }));
}
