/* Diapason — les cartes : deux extrêmes, et toute la graduation entre les deux.
   Toutes écrites pour la Boîte à jeux. Chaque carte = [gauche, droite]. */

'use strict';

const DP_CARDS = [
  ['Froid', 'Chaud'], ['Inutile', 'Indispensable'], ['Sous-coté', 'Surcoté'], ['Facile', 'Difficile'],
  ['Triste', 'Joyeux'], ['Ringard', 'Stylé'], ['Bon marché', 'Hors de prix'], ['Bon pour la santé', 'Mauvais pour la santé'],
  ['Calme', 'Bruyant'], ['Minuscule', 'Gigantesque'], ['Lent', 'Rapide'], ['Rare', 'Partout'],
  ['Moche', 'Magnifique'], ['Ennuyeux', 'Passionnant'], ['Ancien', 'Moderne'], ['Doux', 'Rugueux'],
  ['Fragile', 'Indestructible'], ['Léger', 'Lourd'], ['Salé', 'Sucré'], ['Mou', 'Dur'],
  ['Sombre', 'Lumineux'], ['Simple', 'Compliqué'], ['Sans danger', 'Mortel'], ['Naturel', 'Artificiel'],
  ['Pour les enfants', 'Pour les adultes'], ['Méchant', 'Gentil'], ['Imaginaire', 'Réel'], ['Démodé', 'À la mode'],
  ['Mauvaise idée', 'Idée de génie'], ['Odeur horrible', 'Odeur délicieuse'], ['Film nul', 'Chef-d’œuvre du cinéma'], ['Chanson ratée', 'Tube absolu'],
  ['Plat raté', 'Plat de chef étoilé'], ['Métier ennuyeux', 'Métier de rêve'], ['Super-pouvoir nul', 'Super-pouvoir génial'], ['Cadeau raté', 'Cadeau parfait'],
  ['Animal de compagnie nul', 'Animal de compagnie idéal'], ['Mauvais prénom pour un chien', 'Prénom parfait pour un chien'], ['Nul pour un premier rendez-vous', 'Parfait pour un premier rendez-vous'], ['Pas du tout français', 'Très français'],
  ['Pas drôle du tout', 'Hilarant'], ['Tout le monde adore', 'Tout le monde déteste'], ['Petite bêtise', 'Crime impardonnable'], ['Facile à dessiner', 'Impossible à dessiner'],
  ['Facile à épeler', 'Impossible à épeler'], ['Facile à prononcer', 'Imprononçable'], ['Meilleur froid', 'Meilleur chaud'], ['Petit-déjeuner', 'Dîner'],
  ['Hiver', 'Été'], ['Campagne', 'Grande ville'], ['Mer', 'Montagne'], ['Plutôt chat', 'Plutôt chien'],
  ['Intello', 'Sportif'], ['Introverti', 'Extraverti'], ['Pas cher à entretenir', 'Ruineux à entretenir'], ['Inutile face aux zombies', 'Indispensable face aux zombies'],
  ['Sent le renfermé', 'Sent le propre'], ['Déco de mamie', 'Déco d’influenceur'], ['Talent inutile', 'Talent utile'], ['Sport de paresseux', 'Sport extrême'],
  ['Jeu de société tranquille', 'Jeu qui finit en dispute'], ['Compliment', 'Insulte'], ['Rassurant', 'Flippant'], ['Mignon', 'Terrifiant'],
  ['Pour les bébés', 'Pour les papis'], ['Lassant au bout de cinq minutes', 'Addictif'], ['Se dit à voix haute', 'Se pense tout bas'], ['Excuse bidon', 'Excuse imparable'],
  ['Pieux mensonge', 'Énorme mensonge'], ['Inconnu', 'Mondialement célèbre'], ['Années 80', 'Années 2020'], ['Écolo', 'Pollueur'],
  ['Honnête', 'Malhonnête'], ['Crédible', 'Complètement faux'], ['Discret', 'Tape-à-l’œil'], ['Chic', 'Beauf'],
  ['Normal', 'Bizarre'], ['Réaliste', 'Science-fiction'], ['Relaxant', 'Stressant'], ['Parfaitement sensé', 'Complètement fou'],
  ['Propre', 'Crado'], ['Liquide', 'Solide'], ['Meilleur cru', 'Meilleur cuit'], ['Pire moment de la journée', 'Meilleur moment de la journée'],
  ['Appris en cinq minutes', 'Une vie ne suffit pas'], ['Petit souci', 'Catastrophe'], ['Tâche ménagère agréable', 'Tâche ménagère horrible'], ['Mauvaise habitude', 'Bonne habitude'],
  ['Mauvaise raison de rompre', 'Excellente raison de rompre'], ['Vacances ratées', 'Vacances de rêve'], ['Pire endroit pour dormir', 'Meilleur endroit pour dormir'], ['Film pour pleurer', 'Film pour rire'],
  ['Repas de tous les jours', 'Repas de fête'], ['Musique de mariage', 'Musique d’enterrement'], ['Pas sexy du tout', 'Terriblement sexy'], ['Gênant', 'Impressionnant'],
  ['Prévisible', 'Surprenant'], ['Slogan raté', 'Slogan génial'], ['Personnage secondaire', 'Héros principal'], ['Méchant de film ridicule', 'Méchant de film terrifiant'],
  ['Robot', 'Humain'], ['Fruit', 'Légume'], ['Petit plaisir', 'Immense bonheur'], ['Fade', 'Très épicé'],
  ['Croustillant', 'Fondant'], ['Ça se partage', 'Ça ne se partage pas'], ['Basique', 'Luxueux'], ['Magique', 'Scientifique'],
  ['Très jeune', 'Très vieux'], ['Plutôt la nuit', 'Plutôt le jour'], ['Tradition', 'Innovation'], ['Célébrité adorée', 'Célébrité détestée'],
  ['Superstition absurde', 'Superstition raisonnable'], ['Mal payé', 'Bien payé'], ['Métier dangereux', 'Métier sans aucun risque'], ['Chanson pour danser', 'Chanson pour pleurer'],
  ['Tue-l’amour', 'Irrésistible'], ['À faire seul', 'À faire à plusieurs'], ['Petit budget', 'Budget de superproduction'], ['Très local', 'Mondial'],
  ['Eau', 'Feu'], ['Bruit apaisant', 'Bruit insupportable'], ['Inutile en voyage', 'Indispensable en voyage'], ['Tatouage regrettable', 'Tatouage génial'],
  ['Question facile', 'Question piège'], ['Mauvaise surprise', 'Bonne surprise'], ['Technologie', 'Nature'], ['Snob', 'Populaire'],
  ['Débutant', 'Expert'], ['Réconfortant', 'Dérangeant'], ['Kitsch', 'Élégant'], ['Rond', 'Pointu'],
  ['Tiède', 'Brûlant'], ['Chanceux', 'Malchanceux'], ['Pire invention', 'Meilleure invention'], ['Truc de riche', 'Truc de fauché'],
  ['Truc de Parisien', 'Truc de provincial'], ['Truc de boomer', 'Truc de jeune'], ['Pour l’apéro', 'Pour le dessert'], ['Collant', 'Glissant'],
  ['Vieillit mal', 'Vieillit bien'], ['Bien caché', 'Évident'], ['Poli', 'Malpoli'], ['Modeste', 'Prétentieux'],
  ['On le garde', 'On le jette'], ['Délicieux dans une soupe', 'Horrible dans une soupe'], ['Nom de groupe de rock raté', 'Nom de groupe de rock génial'], ['Nom de bateau raté', 'Nom de bateau génial'],
  ['Mauvais conseil', 'Excellent conseil'], ['Ne se prête jamais', 'Se prête volontiers'], ['Personne ne le fait', 'Tout le monde le fait'], ['Trop court', 'Trop long'],
  ['Film d’horreur gentillet', 'Film d’horreur traumatisant'], ['Dessin animé oublié', 'Dessin animé culte'], ['Facile à garder secret', 'Impossible à garder secret'], ['Normal au petit-déjeuner', 'Bizarre au petit-déjeuner'],
  ['Poids plume', 'Poids lourd'], ['Vrai ami', 'Faux ami'], ['Pour la vie', 'Pour un soir'], ['Mauvais pour un premier emploi', 'Parfait pour un premier emploi'],
  ['Bon perdant', 'Mauvais perdant'], ['Pas du tout romantique', 'Très romantique'], ['Plutôt thé', 'Plutôt café'], ['Mérite le Nobel', 'Mérite la prison'],
  ['Inoffensif', 'Toxique'], ['Organisé', 'Bordélique'], ['Classique', 'Original'], ['Qui dure une seconde', 'Qui dure une éternité'],
  ['Pire son de réveil', 'Meilleur son de réveil'], ['Nul en karaoké', 'Parfait en karaoké'], ['Petit creux', 'Faim de loup'], ['Talent caché', 'Talent évident'],
  ['Utile en cas de panne de courant', 'Inutile en cas de panne de courant'], ['Arnaque', 'Bonne affaire'], ['Qui fait peur aux enfants', 'Qui fait peur aux adultes'], ['Mauvais endroit pour une demande en mariage', 'Endroit parfait pour une demande en mariage'],
];
