/* Cartes de Hors Limite, écrites pour la Boîte à jeux.
   Questions : « _ » marque un trou (une ou deux cartes réponses). Une carte qui commence par « ! »
   est épicée : elle disparaît en mode « soft ». */

'use strict';

const HL_QUESTIONS = [
  'Le secret d’un mariage heureux ? _.',
  'Mon psy dit que tous mes problèmes viennent de _.',
  'Ce soir au journal de 20 h : _ sème la panique à Clermont-Ferrand.',
  'J’ai été viré pour _.',
  'La nouvelle émission de M6 : « _ chez l’habitant ».',
  'Pour mon anniversaire, j’ai demandé _.',
  'Rien ne vaut un dimanche soir avec _.',
  'Le prochain film Pixar raconte l’histoire de _.',
  'Ma grand-mère ne se remet toujours pas de _.',
  'Ce qui m’empêche de dormir la nuit : _.',
  'La vraie raison de la chute de l’Empire romain : _.',
  'En 2050, on apprendra aux enfants à l’école _.',
  'Le Tinder des retraités s’appelle « _ ».',
  'Mon talent caché : _.',
  'Mon dernier achat à 3 h du matin : _.',
  'C’est mon premier rendez-vous et j’ai tout gâché avec _.',
  'Le plat signature du chef étoilé : _ en sauce.',
  'Pourquoi je suis en retard ? _.',
  'La devise de notre famille : « Toujours _ ».',
  'Le nouveau parfum de Chanel sent _.',
  'Les scientifiques sont formels : _ rend plus intelligent.',
  'Au fond du sac de ma mère, on a retrouvé _.',
  'Le seul truc qui peut sauver la planète : _.',
  'Mon coloc a laissé _ dans le frigo.',
  'La meilleure façon de rompre ? _.',
  'Dans mon testament, je lègue à mes enfants _.',
  'Le concept du nouveau restaurant branché : _ à volonté.',
  'Mon mec m’a quittée pour _.',
  'Ma copine m’a quitté à cause de _.',
  'La prochaine épreuve de Koh-Lanta : _.',
  'La chose la plus française du monde : _.',
  'Le Pape a confessé _.',
  'À l’enterrement de ma tante, tout le monde parlait de _.',
  'L’IA a pris le contrôle du monde, et sa première décision est _.',
  'Mon superpouvoir serait _.',
  'Le nouveau jeu de société qui fait fureur : « _, le jeu ».',
  'Qu’est-ce qui sent bizarre dans le bus ? _.',
  'Mon horoscope du jour : attention à _.',
  'Pourquoi le chat me regarde comme ça ? _.',
  'Le cadeau de Noël le plus nul de ma vie : _.',
  'Le nouveau slogan du gouvernement : « _, c’est l’avenir ».',
  'Ma recette pour une soirée réussie : _.',
  'Ce que les voisins entendent à travers le mur : _.',
  'La leçon que la vie m’a apprise : _.',
  'Le prof de sport nous a fait faire _.',
  'Aux urgences, j’ai dû expliquer _.',
  'Pour garder la ligne, je mise tout sur _.',
  'La vidéo virale de la semaine : _.',
  'Ma prochaine tattoo : _.',
  'Le dernier truc que j’ai googlé : « comment se débarrasser de _ ».',
  'L’invité surprise du mariage : _.',
  'Au Salon de l’agriculture, le président a caressé _.',
  'Le nouveau challenge TikTok consiste à _.',
  'Ma plus grande honte : _.',
  'Le sujet du bac philo : « Peut-on vivre sans _ ? »',
  'Mon ex, c’était un peu comme _.',
  'Le vrai nom du Père Noël : _.',
  'Mon grand-père combattait _ pendant la guerre.',
  'Ce qui se passe à Las Vegas reste à Las Vegas, sauf _.',
  'Le secret de la longévité des Japonais : _.',
  'Le musée du Louvre expose désormais _.',
  'Au repas de famille, tonton a encore parlé de _.',
  'Mon compte Instagram est rempli de _.',
  'Le dernier cri de la mode parisienne : _.',
  'J’ai perdu 10 kilos grâce à _.',
  '!Ce soir, pour pimenter notre couple : _.',
  '!Le nouveau jouet du sex-shop : _.',
  '!Ma première fois, c’était avec _.',
  '!Ce que j’ai trouvé dans l’historique de mon père : _.',
  '!Mon fantasme inavouable : _.',
  '!La position préférée des Français : _.',
  // deux trous : on pose deux cartes, dans l'ordre
  '_ + _ = la soirée parfaite.',
  'Dans le nouveau Marvel, _ affronte _.',
  'Je n’échangerais _ contre rien au monde, sauf _.',
  'D’abord _, et ensuite _.',
  'La recette de ma grand-mère : _ mijoté dans _.',
  'Mon CV en deux mots : _ et _.',
  'Le procès de l’année : _ contre _.',
  'On ne mélange pas _ et _.',
  'Mon rêve : _ sur une plage avec _.',
  '!Au lit, j’aime _, mais ma copine préfère _.',
  'Le premier ministre annonce _ pour lutter contre _.',
  'Sans _, pas de _.',
];

const HL_ANSWERS = [
  'Un raton laveur en colère', 'Les impôts', 'Ma belle-mère', 'Une crise de la quarantaine', 'Les chaussettes dans les sandales',
  'Un karaoké de Céline Dion', 'Le wifi de McDo', 'Jean-Pierre Pernaut', 'Une raclette en plein été', 'Un stagiaire non payé',
  'Les pieds de mon oncle', 'La Macarena', 'Un PowerPoint de 80 diapositives', 'Mon compte en banque', 'Un tupperware sans couvercle',
  'Les restes de la veille', 'Un pigeon sous cocaïne', 'La mamie du deuxième étage', 'Un rappeur belge', 'Des croquettes pour chat',
  'La calvitie', 'Un plan à trois avec des Schtroumpfs', 'Le fromage qui pue', 'Un chèque en bois', 'La saison 8 de Game of Thrones',
  'Un abonnement à la salle de sport jamais utilisé', 'Mes photos de vacances à Palavas', 'La crise existentielle d’un pingouin', 'Un poney perdu sans GPS', 'Le Minitel',
  'Un livre de développement personnel', 'Un pédiluve municipal', 'Les ongles de pieds de ma coloc', 'Un réveil qui sonne à 5 h', 'La barbe de mon père',
  'Un rendez-vous chez le dentiste', 'Des cuisses de grenouille', 'Un sanglier des Ardennes', 'Les Enfoirés', 'Un influenceur à Dubaï',
  'Le Bescherelle', 'Une vieille cassette VHS', 'Un clown triste', 'La TVA', 'Un marathon de Plus belle la vie',
  'Une chèvre qui crie', 'Les verres de contact de Mémé', 'Une trottinette électrique abandonnée', 'Mon premier amour', 'Un coup de soleil sur les fesses',
  'Le sourire de Stéphane Bern', 'Des frites trop cuites', 'Un bébé qui juge', 'Le silence gênant après une blague', 'Un kit de survie du Lidl',
  'Les ronflements de mon mari', 'Une sieste de quatre heures', 'Un gilet jaune', 'Un chihuahua enragé', 'L’odeur du RER B',
  'Le curé du village', 'Un shot de Ricard tiède', 'Un vendeur de chez Darty', 'Un cours de zumba', 'Les boules Quies',
  'Un lama qui crache', 'Mon ex qui like mes stories', 'Une huître pas fraîche', 'Les aventures de Oui-Oui', 'Un parapluie retourné par le vent',
  'Le petit doigt en l’air', 'Une cravate à motif Mickey', 'Un contrôleur fiscal', 'Un pâté en croûte', 'Les chansons de Patrick Sébastien',
  'Un mariage à Las Vegas', 'Mon voisin du dessus', 'Une moustache de hipster', 'Un bol de soupe froide', 'La danse des canards',
  'Un club de lecture de mamies déchaînées', 'Les courbatures du lendemain', 'Un pot-de-vin', 'Le cousin qui vend des cryptomonnaies', 'Une coupe mulet',
  'Un tatouage raté en chinois', 'Des moules-frites', 'Une thérapie de couple', 'Les notifications de LinkedIn', 'Un escape game raté',
  'Mon chef de service', 'Un camping-car en panne', 'La coupe du monde de pétanque', 'Des lingettes pour bébé', 'Un mime qui parle',
  'La photo de classe de CM2', 'Un plateau de fruits de mer', 'Une carte Pokémon holographique', 'La vieille voisine qui espionne', 'Des chaussures à roulettes',
  'Un bouc émissaire', 'La fondue savoyarde', 'Un poster de Johnny Hallyday', 'Un cours d’aquagym', 'La mauvaise haleine du matin',
  'Mon abonnement Netflix partagé avec douze personnes', 'Une piñata remplie de brocolis', 'Le discours de Nouvel An du président', 'Un escargot de Bourgogne', 'Un GPS qui ment',
  'Une chanson de Jul', 'Une file d’attente à la Poste', 'Le rire de Jean-Marie Bigard', 'Un béret et une baguette', 'Une démission par SMS',
  'Des toilettes turques', 'Une pizza à l’ananas', 'Un voyant qui ne voit rien', 'Des chaussettes dépareillées', 'Un gynécologue en vacances',
  'Le premier rendez-vous Tinder de mon père', 'Un combat de catch entre mamies', 'Un tonneau de vin rouge', 'Les lunettes de soleil la nuit', 'Une tenue de licorne',
  'Un grille-pain qui brûle tout', 'La fin du monde', 'Un sandwich triangle de station-service', 'Le dernier Jurassic Park', 'Un repas de Noël qui dégénère',
  'Mon avocat, maître Gimsdé', 'Une poule qui pond des œufs en chocolat', 'Un cours de yoga pour chats', 'Les cheveux dans le siphon', 'Un monocycle',
  'La grève de la SNCF', 'Le frère caché de Jésus', 'Des œufs mimosa', 'Le code de la route', 'Un voisin qui fait de la batterie à minuit',
  'La reine d’Angleterre en hologramme', 'Un hamster en déprime', 'Un plombier polonais', 'Des pantoufles chauffantes', 'Un pain au chocolat (ou une chocolatine)',
  'Le carrelage de la salle de bain', 'Un enfant qui dit la vérité', 'Les Bronzés font du ski', 'Une paire de Crocs dorées', 'Un chef scout autoritaire',
  'Un morceau de camembert oublié dans la voiture', 'Des vacances à Center Parcs', 'Mon score au code', 'Un test de grossesse', 'Une centrale nucléaire',
  'Le cri du chameau', 'Un ours en peluche maudit', 'Des dreadlocks sur un chauve', 'Un pneu crevé', 'La mayonnaise qui ne prend pas',
  'Une infirmière très directe', 'Un poisson rouge amnésique', 'Un buffet à volonté', 'La politique étrangère de la Belgique', 'Un rôti de porc',
  'Mes impôts locaux', 'Une conférence sur la tapisserie', 'La reprise du boulot', 'Un bonnet de bain à fleurs', 'Des flatulences en réunion',
  'Une soirée diapositives chez tonton', 'Un vélo sans selle', 'Une pastèque piégée', 'Une teinture blonde ratée', 'Des cris de guerre vikings',
  'La nostalgie des années 90', 'Un cafard volant', 'Une barre de céréales périmée', 'Le troisième verre de trop', 'Un aspirateur robot rebelle',
  'Un DJ qui passe du Francky Vincent', 'La cave de mes grands-parents', 'Un bain moussant', 'Un cascadeur à la retraite', 'Le patron du bar-tabac',
  'Une vidéo de chatons', 'Une soirée mousse à Ibiza', 'Des lasagnes surgelées', 'Le dernier iPhone', 'Une manifestation de clowns',
  'Un requin végétarien', 'La crème anti-rides de maman', 'Un enterrement de vie de garçon à Prague', 'Une poignée de main trop longue', 'Le jambon-beurre',
  'Un bébé panda', 'La chorale de l’église', 'Un moine tibétain', 'Des bigoudis', 'Une caméra cachée',
  'Un ticket de loto gagnant perdu', 'Un duel de regards', 'Des lunettes 3D', 'Un chien qui parle', 'Une danse de la joie',
  'Les inondations du sous-sol', 'Un sorcier vaudou', 'Une nuit blanche', 'Des cornichons', 'Un pyjama une pièce',
  'La crise de nerfs du prof', 'Un bouquet de fleurs fanées', 'Un sac banane', 'Les anciens de l’armée', 'Un cours de salsa',
  'Un youtubeur qui pleure', 'Des fautes d’orthographe', 'Un vieux chewing-gum sous la table', 'Un cheval de course à la retraite', 'Une invasion de sauterelles',
  'La pétanque du dimanche', 'Un DVD de Louis de Funès', 'Un jeu de mots nul', 'La queue au Carrefour un samedi', 'Un colis perdu',
  'Des cheveux dans la soupe', 'Un mannequin de vitrine', 'Une chasse au trésor', 'Un plan foireux', 'La musique d’ascenseur',
  'Le mec qui fait des blagues de beauf', 'Un bébé phoque', 'Une coloscopie', 'La finale de la Coupe du monde 98', 'Un taxidermiste',
  'Un vrai cow-boy', 'Des carottes râpées', 'Le jus de chaussette du bureau', 'Un tournoi de Mario Kart', 'Une nuit au camping sous la pluie',
  'Des extensions de cils', 'La queue de cheval de Karl Lagerfeld', 'Un marathon sans entraînement', 'Une facture d’électricité', 'Un zombie poli',
  'Un apéro qui finit à 6 h', 'Le fils du boulanger', 'Des bottes en caoutchouc', 'Les mains moites', 'Une valise à roulettes cassée',
  'La vaisselle qui traîne', 'Un anniversaire oublié', 'Un nain de jardin', 'Un vol low cost', 'Une réunion Teams sans fin',
  'Un gratin dauphinois', 'La sirène du premier mercredi du mois', 'Des pingouins en smoking', 'Un pot de Nutella vide', 'La belle-sœur trop parfaite',
  '!Un préservatif périmé', '!Un plan cul qui tourne mal', '!Un string léopard', '!Des menottes en fourrure', '!Un appel vidéo au mauvais moment',
  '!Une nuit torride avec un douanier', '!Les voisins qui font l’amour trop fort', '!Un massage qui dérape', '!Un vibromasseur qui s’allume dans le sac', '!Les fesses de mon prof de sport',
  '!Une photo de moi nu sur internet', '!Un club échangiste de province', '!Le kamasutra illustré', '!Une gueule de bois monumentale', '!Un strip-tease de mon oncle',
  '!Un suçon géant', '!Un rendez-vous chez le proctologue', '!Des toilettes de boîte de nuit', '!Le lit qui grince', '!Une huile de massage à la moutarde',
  'Un ministre en slip', 'Un bébé qui boit un café', 'Une tempête de neige en août', 'Les sanglots de Bernard', 'Un couscous royal',
  'Une chorégraphie de Beyoncé', 'Un vendeur de tapis', 'Un pingouin qui fait du ski', 'Une combinaison de ski fluo des années 80', 'Un tracteur tuné',
  'Le petit chat de la voisine', 'Une gâchette facile', 'Un album de Francis Cabrel', 'La patience de ma mère', 'Une pile qui fuit',
  'Des pâtes au beurre', 'Un voyage en Ardèche', 'Une photo floue', 'Un chanteur d’opéra', 'Un robot aspirateur qui a tout vu',
  'Une révolution', 'Un poulet rôti', 'Le RSA', 'Un pull de Noël qui clignote', 'Un vieux Nokia 3310',
  'Des glaçons', 'Un bébé koala', 'Un cheval', 'Le vent', 'Du papier toilette', 'La pluie', 'Une licorne', 'Mon oncle', 'Un moustique', 'Un chat',
];
