# -*- coding: utf-8 -*-
"""Questions maison pour Camembert, en complément de quiz.json (quizzapi.fr).
Format : (couleur, difficulté 1-3, question, bonne réponse, [trois mauvaises]).
Lancer : python quiz-extra.py  -> écrit quiz-extra.json (fusionné par le jeu avec quiz.json)."""
import json, os

Q = [
# ---------------------------------------------------------------- Géographie (geo)
('geo', 1, "Quelle est la capitale de l'Australie ?", 'Canberra', ['Sydney', 'Melbourne', 'Perth']),
('geo', 1, 'Quel est le plus long fleuve de France ?', 'La Loire', ['La Seine', 'Le Rhône', 'La Garonne']),
('geo', 1, 'Dans quel pays se trouve le Machu Picchu ?', 'Le Pérou', ['Le Chili', 'La Bolivie', 'Le Mexique']),
('geo', 1, 'Quel océan borde la côte ouest des États-Unis ?', "L'océan Pacifique", ["L'océan Atlantique", "L'océan Indien", "L'océan Arctique"]),
('geo', 1, 'Quelle est la capitale du Canada ?', 'Ottawa', ['Toronto', 'Montréal', 'Vancouver']),
('geo', 1, "Quel est le plus grand désert chaud du monde ?", 'Le Sahara', ['Le Gobi', 'Le Kalahari', "L'Atacama"]),
('geo', 1, 'Dans quel pays se trouve la ville de Marrakech ?', 'Le Maroc', ["L'Algérie", 'La Tunisie', "L'Égypte"]),
('geo', 1, "Quel est le plus haut sommet d'Europe occidentale ?", 'Le mont Blanc', ['Le Cervin', 'Le mont Rose', 'Le Grand Paradis']),
('geo', 1, 'Quelle mer sépare la France de l\'Angleterre ?', 'La Manche', ['La mer du Nord', 'La mer d\'Irlande', 'La mer Celtique']),
('geo', 1, 'Quel pays a la forme d\'une botte ?', "L'Italie", ['La Grèce', 'Le Portugal', 'La Croatie']),
('geo', 1, 'Quelle est la capitale du Japon ?', 'Tokyo', ['Kyoto', 'Osaka', 'Séoul']),
('geo', 2, 'Quel est le plus grand pays du monde par la superficie ?', 'La Russie', ['Le Canada', 'La Chine', 'Les États-Unis']),
('geo', 2, 'Quel fleuve traverse Vienne, Budapest et Belgrade ?', 'Le Danube', ['Le Rhin', 'La Vistule', "L'Elbe"]),
('geo', 2, 'Quelle est la capitale de la Nouvelle-Zélande ?', 'Wellington', ['Auckland', 'Christchurch', 'Queenstown']),
('geo', 2, 'Dans quel pays se trouve le lac Titicaca ?', 'Le Pérou et la Bolivie', ['Le Chili et l\'Argentine', "L'Équateur", 'La Colombie']),
('geo', 2, "Quelle île française se trouve dans l'océan Indien ?", 'La Réunion', ['La Martinique', 'La Guadeloupe', 'Saint-Pierre-et-Miquelon']),
('geo', 2, "Quel détroit sépare l'Europe de l'Afrique ?", 'Le détroit de Gibraltar', ['Le Bosphore', 'Le détroit de Messine', 'Le détroit de Béring']),
('geo', 2, 'Quelle est la plus grande île de la Méditerranée ?', 'La Sicile', ['La Sardaigne', 'Chypre', 'La Corse']),
('geo', 2, 'Quel pays compte le plus d\'habitants en Afrique ?', 'Le Nigeria', ["L'Éthiopie", "L'Égypte", 'La RD Congo']),
('geo', 2, 'Dans quel département se trouve le Mont-Saint-Michel ?', 'La Manche', ['Le Calvados', "L'Ille-et-Vilaine", 'Les Côtes-d\'Armor']),
('geo', 2, 'Quelle est la capitale de la Suisse ?', 'Berne', ['Zurich', 'Genève', 'Lausanne']),
('geo', 2, "Quel est le plus grand lac d'Afrique ?", 'Le lac Victoria', ['Le lac Tanganyika', 'Le lac Malawi', 'Le lac Tchad']),
('geo', 2, 'Quel pays est bordé à la fois par la mer Noire et la mer Méditerranée ?', 'La Turquie', ['La Bulgarie', 'La Grèce', 'La Roumanie']),
('geo', 2, "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", "L'Oural", ['Le Caucase', 'Les Carpates', "L'Altaï"]),
('geo', 2, 'Quelle ville est la capitale de la Catalogne ?', 'Barcelone', ['Valence', 'Séville', 'Bilbao']),
('geo', 2, 'Quel est le plus petit État du monde ?', 'Le Vatican', ['Monaco', 'Saint-Marin', 'Nauru']),
('geo', 3, 'Quelle est la capitale du Kazakhstan ?', 'Astana', ['Almaty', 'Tachkent', 'Bichkek']),
('geo', 3, 'Quel fleuve forme la frontière entre les États-Unis et le Mexique sur une grande partie de sa longueur ?', 'Le Rio Grande', ['Le Colorado', 'Le Mississippi', 'Le Missouri']),
('geo', 3, "Quel pays d'Amérique du Sud n'a pas d'accès à la mer, comme la Bolivie ?", 'Le Paraguay', ["L'Uruguay", "L'Équateur", 'Le Suriname']),
('geo', 3, 'Quelle est la capitale de la Birmanie (Myanmar) depuis 2005 ?', 'Naypyidaw', ['Rangoun', 'Mandalay', 'Bagan']),
('geo', 3, 'Combien de pays ont une frontière terrestre avec la France métropolitaine ?', '8', ['6', '7', '9']),
('geo', 3, 'Quel archipel portugais se trouve au large du Maroc ?', 'Madère', ['Les Açores', 'Les Canaries', 'Le Cap-Vert']),
('geo', 3, 'Quel est le plus long fleuve d\'Europe ?', 'La Volga', ['Le Danube', 'Le Dniepr', 'Le Rhin']),
('geo', 3, 'Dans quel pays se trouve le mont Kilimandjaro ?', 'La Tanzanie', ['Le Kenya', "L'Ouganda", "L'Éthiopie"]),
('geo', 3, 'Quelle ville française est surnommée « la Venise du Nord » ?', 'Amiens', ['Lille', 'Strasbourg', 'Annecy']),
('geo', 3, 'Quel pays a pour capitale Oulan-Bator ?', 'La Mongolie', ['Le Népal', 'Le Kirghizistan', 'Le Bhoutan']),
# ---------------------------------------------------------------- Divertissement (fun)
('fun', 1, 'Dans « Star Wars », qui est le père de Luke Skywalker ?', 'Dark Vador', ['Obi-Wan Kenobi', "L'Empereur", 'Han Solo']),
('fun', 1, 'Quel groupe a chanté « Bohemian Rhapsody » ?', 'Queen', ['The Beatles', 'Led Zeppelin', 'Pink Floyd']),
('fun', 1, 'Quel est le nom du petit poisson-clown perdu dans le film Pixar ?', 'Nemo', ['Dory', 'Marin', 'Bruce']),
('fun', 1, 'Dans « Harry Potter », comment s\'appelle l\'école de sorcellerie ?', 'Poudlard', ['Durmstrang', 'Beauxbâtons', 'Ilvermorny']),
('fun', 1, 'Quel chanteur belge interprète « Formidable » et « Papaoutai » ?', 'Stromae', ['Angèle', 'Jacques Brel', 'Roméo Elvis']),
('fun', 1, 'Quel plombier moustachu est la mascotte de Nintendo ?', 'Mario', ['Luigi', 'Wario', 'Sonic']),
('fun', 1, 'Dans « Les Simpson », comment s\'appelle le père de famille ?', 'Homer', ['Bart', 'Ned', 'Moe']),
('fun', 1, 'Quelle série suit les habitants de Kaamelott, autour du roi Arthur ?', 'Kaamelott', ['Merlin', 'Bref', 'Hero Corp']),
('fun', 2, 'Qui a réalisé « Titanic » et « Avatar » ?', 'James Cameron', ['Steven Spielberg', 'Ridley Scott', 'Peter Jackson']),
('fun', 2, 'Quel film a remporté l\'Oscar du meilleur film en 2020, une première pour un film en langue étrangère ?', 'Parasite', ['1917', 'Joker', 'Roma']),
('fun', 2, 'Quel chanteur français a interprété « Les Copains d\'abord » ?', 'Georges Brassens', ['Jacques Brel', 'Léo Ferré', 'Serge Gainsbourg']),
('fun', 2, 'Dans « Friends », quel est le métier de Chandler, longtemps mystérieux pour ses amis ?', 'Il travaille dans les statistiques et l\'informatique', ['Avocat', 'Chef cuisinier', 'Paléontologue']),
('fun', 2, 'Quel jeu vidéo suédois consiste à construire avec des blocs dans un monde ouvert ?', 'Minecraft', ['Roblox', 'Terraria', 'Fortnite']),
('fun', 2, 'Quel groupe français de musique électronique portait des casques de robots ?', 'Daft Punk', ['Justice', 'Air', 'Cassius']),
('fun', 2, 'Quel acteur incarne Iron Man dans les films Marvel ?', 'Robert Downey Jr.', ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo']),
('fun', 2, 'Dans « Le Seigneur des anneaux », comment s\'appelle le cousin de Frodon qui l\'accompagne avec Pippin ?', 'Merry', ['Sam', 'Bilbon', 'Boromir']),
('fun', 2, 'Quelle chanteuse a sorti l\'album « 1989 » puis « Midnights » ?', 'Taylor Swift', ['Adele', 'Billie Eilish', 'Dua Lipa']),
('fun', 2, 'Quel personnage de jeu vidéo est une chasseuse de trésors nommée Lara ?', 'Lara Croft', ['Samus Aran', 'Aloy', 'Ellie']),
('fun', 2, 'Dans la série « Breaking Bad », quel est le métier initial de Walter White ?', 'Professeur de chimie', ['Pharmacien', 'Policier', 'Avocat']),
('fun', 2, 'Quel humoriste français a créé le personnage de Jean-Claude Duss dans « Les Bronzés » ?', 'Michel Blanc', ['Gérard Jugnot', 'Thierry Lhermitte', 'Christian Clavier']),
('fun', 3, 'Quel compositeur a écrit la musique de « Star Wars », « Indiana Jones » et « Jurassic Park » ?', 'John Williams', ['Hans Zimmer', 'Ennio Morricone', 'Danny Elfman']),
('fun', 3, 'Quelle console Nintendo est sortie en 2017, jouable en salon comme en portable ?', 'La Switch', ['La Wii U', 'La 3DS', 'La GameCube']),
('fun', 3, 'Quel film de 1994 de Quentin Tarantino met en scène Vincent Vega et Jules Winnfield ?', 'Pulp Fiction', ['Reservoir Dogs', 'Jackie Brown', 'Kill Bill']),
('fun', 3, 'Dans « Game of Thrones », comment s\'appelle l\'épée de Jon Snow ?', 'Grand-Griffe (Longclaw)', ['Aiguille', 'Glace', 'Feu-Vif']),
('fun', 3, 'Quel groupe britannique a sorti l\'album « The Dark Side of the Moon » ?', 'Pink Floyd', ['Genesis', 'The Who', 'Radiohead']),
('fun', 3, 'Quel studio a créé « The Legend of Zelda: Breath of the Wild » ?', 'Nintendo', ['Square Enix', 'Capcom', 'Sega']),
('fun', 3, 'Quel réalisateur français a signé « Le Fabuleux Destin d\'Amélie Poulain » ?', 'Jean-Pierre Jeunet', ['Luc Besson', 'Michel Gondry', 'Cédric Klapisch']),
('fun', 3, 'Dans quel jeu affronte-t-on des « Colosses » dans un monde vide et silencieux ?', 'Shadow of the Colossus', ['Dark Souls', 'Ico', 'Journey']),
# ---------------------------------------------------------------- Histoire (hist)
('hist', 1, 'En quelle année a eu lieu la prise de la Bastille ?', '1789', ['1792', '1799', '1804']),
('hist', 1, 'Qui était le premier président des États-Unis ?', 'George Washington', ['Thomas Jefferson', 'Abraham Lincoln', 'Benjamin Franklin']),
('hist', 1, 'Quel roi de France était surnommé le Roi-Soleil ?', 'Louis XIV', ['Louis XVI', 'François Ier', 'Henri IV']),
('hist', 1, 'En quelle année s\'est terminée la Seconde Guerre mondiale ?', '1945', ['1944', '1946', '1918']),
('hist', 1, 'Quel navigateur a atteint l\'Amérique en 1492 ?', 'Christophe Colomb', ['Vasco de Gama', 'Magellan', 'Jacques Cartier']),
('hist', 1, 'Qui a été le premier homme à marcher sur la Lune ?', 'Neil Armstrong', ['Buzz Aldrin', 'Youri Gagarine', 'Michael Collins']),
('hist', 1, 'Quelle reine d\'Égypte a séduit Jules César puis Marc Antoine ?', 'Cléopâtre', ['Néfertiti', 'Hatchepsout', 'Théodora']),
('hist', 1, 'En quelle année le mur de Berlin est-il tombé ?', '1989', ['1991', '1985', '1979']),
('hist', 1, 'Qui a été sacré empereur des Français en 1804 ?', 'Napoléon Bonaparte', ['Louis-Philippe', 'Charles X', 'Napoléon III']),
('hist', 2, 'Quel événement déclenche la Première Guerre mondiale en 1914 ?', "L'assassinat de l'archiduc François-Ferdinand", ["L'invasion de la Pologne", 'Le naufrage du Lusitania', 'La révolution russe']),
('hist', 2, 'Quelle bataille de 1815 marque la défaite finale de Napoléon ?', 'Waterloo', ['Austerlitz', 'Leipzig', 'Trafalgar']),
('hist', 2, 'Qui a dirigé la France libre depuis Londres pendant la Seconde Guerre mondiale ?', 'Charles de Gaulle', ['Jean Moulin', 'Philippe Pétain', 'Georges Clemenceau']),
('hist', 2, 'Quel peuple a construit les pyramides de Chichén Itzá ?', 'Les Mayas', ['Les Aztèques', 'Les Incas', 'Les Olmèques']),
('hist', 2, 'En quelle année les femmes ont-elles voté pour la première fois en France ?', '1945', ['1936', '1919', '1958']),
('hist', 2, 'Quel roi d\'Angleterre a eu six épouses ?', 'Henri VIII', ['Richard III', 'Édouard VI', 'Georges III']),
('hist', 2, 'Quelle ville romaine a été ensevelie par l\'éruption du Vésuve en 79 ?', 'Pompéi', ['Ostie', 'Capoue', 'Naples']),
('hist', 2, 'Quel traité met fin à la Première Guerre mondiale en 1919 ?', 'Le traité de Versailles', ['Le traité de Vienne', 'Le traité de Rome', 'Le traité de Paris']),
('hist', 2, 'Qui a rédigé les « 95 thèses » à l\'origine de la Réforme protestante ?', 'Martin Luther', ['Jean Calvin', 'Érasme', 'Thomas More']),
('hist', 2, 'Quelle dynastie chinoise a fait construire la Cité interdite ?', 'Les Ming', ['Les Qing', 'Les Tang', 'Les Han']),
('hist', 2, 'En quelle année la France a-t-elle adopté l\'euro en pièces et billets ?', '2002', ['1999', '2000', '2004']),
('hist', 2, 'Quel président français a fait abolir la peine de mort en 1981 ?', 'François Mitterrand', ['Valéry Giscard d\'Estaing', 'Jacques Chirac', 'Georges Pompidou']),
('hist', 2, 'Quel empire avait pour capitale Constantinople ?', "L'Empire byzantin", ["L'Empire perse", "L'Empire mongol", "L'Empire carolingien"]),
('hist', 2, 'Qui a été guillotinée en 1793, après son mari Louis XVI ?', 'Marie-Antoinette', ['Madame de Pompadour', 'Charlotte Corday', 'Olympe de Gouges']),
('hist', 3, 'En quelle année Jeanne d\'Arc a-t-elle été brûlée à Rouen ?', '1431', ['1429', '1453', '1415']),
('hist', 3, 'Quel pharaon a fait construire la grande pyramide de Gizeh ?', 'Khéops', ['Ramsès II', 'Toutânkhamon', 'Akhenaton']),
('hist', 3, 'Quel traité de 843 partage l\'empire de Charlemagne entre ses petits-fils ?', 'Le traité de Verdun', ['Le traité de Meerssen', 'Le traité de Saint-Clair-sur-Epte', 'Le traité de Troyes']),
('hist', 3, 'Quel dirigeant soviétique a lancé la perestroïka ?', 'Mikhaïl Gorbatchev', ['Leonid Brejnev', 'Nikita Khrouchtchev', 'Boris Eltsine']),
('hist', 3, 'En quelle année a eu lieu la bataille d\'Alésia entre César et Vercingétorix ?', '52 av. J.-C.', ['31 av. J.-C.', '100 av. J.-C.', '9 ap. J.-C.']),
('hist', 3, 'Quelle épidémie a tué environ un tiers des Européens au milieu du XIVe siècle ?', 'La peste noire', ['Le choléra', 'La variole', 'La grippe espagnole']),
('hist', 3, 'Qui a été le premier ministre britannique pendant la majeure partie de la Seconde Guerre mondiale ?', 'Winston Churchill', ['Neville Chamberlain', 'Clement Attlee', 'Anthony Eden']),
('hist', 3, 'Quel explorateur portugais a été le premier à contourner le cap de Bonne-Espérance en 1488 ?', 'Bartolomeu Dias', ['Vasco de Gama', 'Henri le Navigateur', 'Pedro Álvares Cabral']),
('hist', 3, 'Quel accord de 1998 a mis fin au conflit en Irlande du Nord ?', "L'accord du Vendredi saint", ["L'accord de Dayton", "L'accord d'Oslo", "L'accord de Camp David"]),
('hist', 3, 'Quelle république a précédé la Ve République française, proclamée en 1958 ?', 'La IVe République', ['La IIIe République', 'La IIe République', "L'État français"]),
# ---------------------------------------------------------------- Arts & Littérature (art)
('art', 1, 'Qui a peint « La Joconde » ?', 'Léonard de Vinci', ['Michel-Ange', 'Raphaël', 'Botticelli']),
('art', 1, 'Qui a écrit « Les Misérables » ?', 'Victor Hugo', ['Émile Zola', 'Alexandre Dumas', 'Honoré de Balzac']),
('art', 1, 'Quel peintre s\'est coupé une partie de l\'oreille ?', 'Vincent van Gogh', ['Paul Gauguin', 'Claude Monet', 'Pablo Picasso']),
('art', 1, 'Qui a écrit « Le Petit Prince » ?', 'Antoine de Saint-Exupéry', ['Jules Verne', 'Marcel Pagnol', 'Albert Camus']),
('art', 1, 'Quel auteur a créé le détective Sherlock Holmes ?', 'Arthur Conan Doyle', ['Agatha Christie', 'Edgar Allan Poe', 'Charles Dickens']),
('art', 1, 'Quel musée parisien abrite « La Joconde » ?', 'Le Louvre', ["Le musée d'Orsay", 'Le Centre Pompidou', 'Le Grand Palais']),
('art', 1, 'Quel peintre espagnol a réalisé « Guernica » ?', 'Pablo Picasso', ['Salvador Dalí', 'Joan Miró', 'Francisco de Goya']),
('art', 1, 'Qui a écrit « Roméo et Juliette » ?', 'William Shakespeare', ['Molière', 'Oscar Wilde', 'Jane Austen']),
('art', 1, 'Quel auteur de BD a créé Astérix avec Albert Uderzo ?', 'René Goscinny', ['Hergé', 'Franquin', 'Morris']),
('art', 2, 'Quel sculpteur a réalisé « Le Penseur » ?', 'Auguste Rodin', ['Camille Claudel', 'Antoine Bourdelle', 'Constantin Brancusi']),
('art', 2, 'Quel peintre est connu pour ses « Nymphéas » peints à Giverny ?', 'Claude Monet', ['Édouard Manet', 'Auguste Renoir', 'Paul Cézanne']),
('art', 2, 'Qui a écrit « Madame Bovary » ?', 'Gustave Flaubert', ['Stendhal', 'Guy de Maupassant', 'Émile Zola']),
('art', 2, 'Quel compositeur, devenu sourd, a écrit la Neuvième Symphonie et son « Hymne à la joie » ?', 'Ludwig van Beethoven', ['Mozart', 'Bach', 'Schubert']),
('art', 2, 'Quel roman de George Orwell décrit un État totalitaire dirigé par Big Brother ?', '1984', ['La Ferme des animaux', 'Le Meilleur des mondes', 'Fahrenheit 451']),
('art', 2, 'Qui a peint le plafond de la chapelle Sixtine ?', 'Michel-Ange', ['Léonard de Vinci', 'Raphaël', 'Le Caravage']),
('art', 2, 'Quel écrivain a créé le commissaire Maigret ?', 'Georges Simenon', ['Maurice Leblanc', 'Gaston Leroux', 'Fred Vargas']),
('art', 2, 'Quel mouvement artistique est associé à Salvador Dalí et René Magritte ?', 'Le surréalisme', ["L'impressionnisme", 'Le cubisme', 'Le fauvisme']),
('art', 2, 'Qui a écrit « L\'Étranger » et « La Peste » ?', 'Albert Camus', ['Jean-Paul Sartre', 'André Malraux', 'Simone de Beauvoir']),
('art', 2, 'Quelle pièce de Molière met en scène Harpagon ?', "L'Avare", ['Tartuffe', 'Le Malade imaginaire', 'Les Fourberies de Scapin']),
('art', 2, 'Quel peintre norvégien a réalisé « Le Cri » ?', 'Edvard Munch', ['Gustav Klimt', 'Egon Schiele', 'Wassily Kandinsky']),
('art', 2, 'Qui a écrit « Vingt Mille Lieues sous les mers » ?', 'Jules Verne', ['Alexandre Dumas', 'H. G. Wells', 'Jack London']),
('art', 2, 'Quel auteur a écrit la saga « Le Trône de fer » ?', 'George R. R. Martin', ['J. R. R. Tolkien', 'Terry Pratchett', 'Robin Hobb']),
('art', 2, 'Quel architecte a conçu la tour de 324 mètres inaugurée à Paris en 1889 ?', 'Gustave Eiffel', ['Le Corbusier', 'Baron Haussmann', 'Jean Nouvel']),
('art', 3, 'Quel peintre hollandais a réalisé « La Jeune Fille à la perle » ?', 'Johannes Vermeer', ['Rembrandt', 'Frans Hals', 'Jan Steen']),
('art', 3, 'Qui a écrit « À la recherche du temps perdu » ?', 'Marcel Proust', ['André Gide', 'Louis-Ferdinand Céline', 'Paul Valéry']),
('art', 3, 'Quel compositeur a écrit « Le Boléro » ?', 'Maurice Ravel', ['Claude Debussy', 'Erik Satie', 'Camille Saint-Saëns']),
('art', 3, 'Quel écrivain russe a écrit « Crime et Châtiment » ?', 'Fiodor Dostoïevski', ['Léon Tolstoï', 'Anton Tchekhov', 'Nicolas Gogol']),
('art', 3, 'Quel peintre autrichien a réalisé « Le Baiser », tableau doré de 1908 ?', 'Gustav Klimt', ['Edvard Munch', 'Egon Schiele', 'Oskar Kokoschka']),
('art', 3, 'Quelle romancière a écrit « Orgueil et Préjugés » ?', 'Jane Austen', ['Charlotte Brontë', 'Mary Shelley', 'Virginia Woolf']),
('art', 3, 'Quel poète a écrit « Les Fleurs du mal » ?', 'Charles Baudelaire', ['Arthur Rimbaud', 'Paul Verlaine', 'Stéphane Mallarmé']),
('art', 3, 'Quel artiste américain est célèbre pour ses boîtes de soupe Campbell ?', 'Andy Warhol', ['Roy Lichtenstein', 'Jackson Pollock', 'Keith Haring']),
('art', 3, 'Quel auteur colombien a écrit « Cent ans de solitude » ?', 'Gabriel García Márquez', ['Mario Vargas Llosa', 'Jorge Luis Borges', 'Pablo Neruda']),
('art', 3, 'Quel opéra de Bizet se déroule à Séville, avec une cigarière et un toréador ?', 'Carmen', ['La Traviata', 'Tosca', 'Les Pêcheurs de perles']),
# ---------------------------------------------------------------- Sciences & Nature (sci)
('sci', 1, 'Quelle planète est la plus proche du Soleil ?', 'Mercure', ['Vénus', 'Mars', 'La Terre']),
('sci', 1, 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', 'Le dioxyde de carbone', ["L'oxygène", "L'azote", "L'hydrogène"]),
('sci', 1, "Combien d'os compte le squelette d'un adulte, environ ?", '206', ['106', '306', '412']),
('sci', 1, 'Quel est le plus grand animal vivant sur Terre ?', 'La baleine bleue', ["L'éléphant d'Afrique", 'Le requin-baleine', 'La girafe']),
('sci', 1, 'Quel est le symbole chimique de l\'or ?', 'Au', ['Or', 'Ag', 'Go']),
('sci', 1, 'À quelle température l\'eau bout-elle au niveau de la mer ?', '100 °C', ['90 °C', '110 °C', '120 °C']),
('sci', 1, 'Quel organe pompe le sang dans le corps ?', 'Le cœur', ['Le foie', 'Les poumons', 'Les reins']),
('sci', 1, 'Combien de pattes a une araignée ?', '8', ['6', '10', '12']),
('sci', 1, 'Quelle planète est surnommée la planète rouge ?', 'Mars', ['Jupiter', 'Vénus', 'Saturne']),
('sci', 2, 'Quel scientifique a formulé la théorie de la relativité ?', 'Albert Einstein', ['Isaac Newton', 'Galilée', 'Niels Bohr']),
('sci', 2, 'Quel est l\'élément chimique le plus abondant dans l\'univers ?', "L'hydrogène", ["L'hélium", "L'oxygène", 'Le carbone']),
('sci', 2, 'Quelle est la vitesse de la lumière dans le vide, environ ?', '300 000 km/s', ['30 000 km/s', '3 000 000 km/s', '150 000 km/s']),
('sci', 2, 'Quelle molécule porte l\'information génétique ?', "L'ADN", ["L'ATP", 'Le glucose', "L'hémoglobine"]),
('sci', 2, 'Qui a découvert la pénicilline en 1928 ?', 'Alexander Fleming', ['Louis Pasteur', 'Marie Curie', 'Robert Koch']),
('sci', 2, 'Quelle est la plus grande planète du système solaire ?', 'Jupiter', ['Saturne', 'Neptune', 'Uranus']),
('sci', 2, 'Combien de chromosomes possède une cellule humaine ?', '46', ['23', '48', '64']),
('sci', 2, 'Quel métal est liquide à température ambiante ?', 'Le mercure', ['Le plomb', "L'étain", 'Le sodium']),
('sci', 2, 'Quelle est l\'unité de mesure de la force ?', 'Le newton', ['Le joule', 'Le watt', 'Le pascal']),
('sci', 2, 'Quel animal a le cœur le plus gros au monde ?', 'La baleine bleue', ["L'éléphant", 'La girafe', 'Le grand requin blanc']),
('sci', 2, 'Quelle partie du cerveau contrôle l\'équilibre et la coordination ?', 'Le cervelet', ["L'hippocampe", 'Le cortex frontal', "L'hypothalamus"]),
('sci', 2, 'Quel est le pH d\'une solution neutre ?', '7', ['0', '14', '5']),
('sci', 2, 'Quel os est le plus long du corps humain ?', 'Le fémur', ['Le tibia', "L'humérus", 'La colonne vertébrale']),
('sci', 2, 'Quel phénomène explique que le ciel est bleu ?', 'La diffusion de la lumière par l\'atmosphère', ['Le reflet des océans', "L'ozone", 'La réfraction par les nuages']),
('sci', 3, 'Quelle est la formule chimique de l\'eau oxygénée ?', 'H2O2', ['H2O', 'HO2', 'O3']),
('sci', 3, 'Quel physicien a énoncé le principe d\'incertitude ?', 'Werner Heisenberg', ['Erwin Schrödinger', 'Max Planck', 'Paul Dirac']),
('sci', 3, 'Quel est le nom de la plus grande lune de Saturne ?', 'Titan', ['Europe', 'Ganymède', 'Encelade']),
('sci', 3, 'Combien de temps la lumière du Soleil met-elle pour atteindre la Terre, environ ?', '8 minutes', ['8 secondes', '8 heures', '1 minute']),
('sci', 3, 'Quel savant a proposé la classification périodique des éléments en 1869 ?', 'Dmitri Mendeleïev', ['Antoine Lavoisier', 'John Dalton', 'Marie Curie']),
('sci', 3, 'Quelle est la particule de charge positive du noyau atomique ?', 'Le proton', ["L'électron", 'Le neutron', 'Le photon']),
('sci', 3, 'Quel est le seul mammifère capable de voler véritablement ?', 'La chauve-souris', ["L'écureuil volant", 'Le colugo', 'Le phalanger']),
('sci', 3, 'Combien de cœurs possède une pieuvre ?', '3', ['1', '2', '4']),
('sci', 3, 'Quelle échelle mesure la magnitude des séismes ?', "L'échelle de Richter", ["L'échelle de Beaufort", "L'échelle de Mohs", "L'échelle de Kelvin"]),
('sci', 3, 'Quel élément chimique a pour numéro atomique 6 ?', 'Le carbone', ["L'oxygène", "L'azote", 'Le bore']),
('sci', 3, 'Quel naturaliste a publié « De l\'origine des espèces » en 1859 ?', 'Charles Darwin', ['Jean-Baptiste de Lamarck', 'Gregor Mendel', 'Alfred Wallace']),
# ---------------------------------------------------------------- Sports & Loisirs (sport)
('sport', 1, 'Combien de joueurs compte une équipe de football sur le terrain ?', '11', ['10', '12', '9']),
('sport', 1, 'Dans quel sport utilise-t-on un volant ?', 'Le badminton', ['Le squash', 'Le tennis de table', 'Le padel']),
('sport', 1, 'Quel pays a remporté la Coupe du monde de football 2018 ?', 'La France', ['La Croatie', 'La Belgique', "L'Allemagne"]),
('sport', 1, 'Combien de points vaut un essai au rugby à XV ?', '5', ['3', '4', '7']),
('sport', 1, 'Dans quelle ville se sont déroulés les Jeux olympiques d\'été 2024 ?', 'Paris', ['Los Angeles', 'Tokyo', 'Londres']),
('sport', 1, 'Quel sport se pratique à Roland-Garros ?', 'Le tennis', ['Le golf', 'Le polo', "L'équitation"]),
('sport', 1, 'Quelle est la couleur du maillot du leader du Tour de France ?', 'Jaune', ['Vert', 'Blanc', 'À pois rouges']),
('sport', 1, 'Combien de cases compte un échiquier ?', '64', ['32', '81', '100']),
('sport', 1, 'Quel nageur américain détient le record de médailles d\'or olympiques ?', 'Michael Phelps', ['Mark Spitz', 'Ryan Lochte', 'Ian Thorpe']),
('sport', 2, 'Quel joueur a remporté le plus de titres à Roland-Garros ?', 'Rafael Nadal', ['Björn Borg', 'Roger Federer', 'Novak Djokovic']),
('sport', 2, 'Quel pays a inventé le judo ?', 'Le Japon', ['La Chine', 'La Corée', 'Le Brésil']),
('sport', 2, 'Combien de temps dure un match de rugby à XV, hors arrêts de jeu ?', '80 minutes', ['90 minutes', '60 minutes', '70 minutes']),
('sport', 2, 'Quel club français a remporté la Ligue des champions en 1993 ?', "L'Olympique de Marseille", ['Le Paris Saint-Germain', "L'AS Monaco", "L'Olympique lyonnais"]),
('sport', 2, 'Quelle distance parcourt-on lors d\'un marathon ?', '42,195 km', ['40 km', '45 km', '21,1 km']),
('sport', 2, 'Quel sprinteur jamaïcain détient le record du monde du 100 m ?', 'Usain Bolt', ['Carl Lewis', 'Yohan Blake', 'Asafa Powell']),
('sport', 2, 'Dans quel sport parle-t-on de « birdie » et de « bogey » ?', 'Le golf', ['Le bowling', 'Le curling', 'Le cricket']),
('sport', 2, 'Quelle équipe de NBA compte Michael Jordan parmi ses légendes ?', 'Les Chicago Bulls', ['Les Los Angeles Lakers', 'Les Boston Celtics', 'Les Miami Heat']),
('sport', 2, 'Quel pilote a remporté sept titres de champion du monde de Formule 1, comme Michael Schumacher ?', 'Lewis Hamilton', ['Sebastian Vettel', 'Max Verstappen', 'Ayrton Senna']),
('sport', 2, 'Combien de joueurs compte une équipe de basket sur le terrain ?', '5', ['6', '7', '4']),
('sport', 2, 'Quel pays a remporté le plus de Coupes du monde de football ?', 'Le Brésil', ["L'Allemagne", "L'Italie", "L'Argentine"]),
('sport', 2, 'Quel gardien de handball français était surnommé « le Chat » ?', 'Thierry Omeyer', ['Nikola Karabatic', 'Luc Abalo', 'Daniel Narcisse']),
('sport', 2, 'Quelle nageuse française a été championne olympique du 400 m nage libre à Londres en 2012 ?', 'Camille Muffat', ['Laure Manaudou', 'Charlotte Bonnet', 'Coralie Balmy']),
('sport', 2, 'Quel jeu de société se joue avec des lettres et un plateau de cases à bonus ?', 'Le Scrabble', ['Le Monopoly', 'Le Cluedo', 'Le Risk']),
('sport', 3, 'En quelle année la France a-t-elle remporté sa première Coupe du monde de football ?', '1998', ['1984', '2000', '2006']),
('sport', 3, 'Quel cycliste a remporté cinq Tours de France dans les années 1990 avant d\'être déchu ?', 'Lance Armstrong', ['Miguel Indurain', 'Jan Ullrich', 'Marco Pantani']),
('sport', 3, 'Quelle ville a accueilli les premiers Jeux olympiques modernes en 1896 ?', 'Athènes', ['Paris', 'Londres', 'Rome']),
('sport', 3, 'Combien de Grands Chelems compte le tennis chaque année ?', '4', ['3', '5', '6']),
('sport', 3, 'Quel boxeur, né Cassius Clay, a été champion du monde des poids lourds ?', 'Mohamed Ali', ['Joe Frazier', 'George Foreman', 'Mike Tyson']),
('sport', 3, 'Dans quel sport s\'illustre Teddy Riner ?', 'Le judo', ['La lutte', 'Le karaté', 'Le taekwondo']),
('sport', 3, 'Quel pays a remporté la Coupe du monde de rugby 2023 ?', "L'Afrique du Sud", ['La Nouvelle-Zélande', 'La France', "L'Irlande"]),
('sport', 3, 'Combien de points vaut la bille noire au snooker ?', '7', ['5', '6', '8']),
('sport', 3, 'Quel footballeur a marqué de la main lors du quart de finale Argentine-Angleterre en 1986 ?', 'Diego Maradona', ['Gabriel Batistuta', 'Mario Kempes', 'Jorge Valdano']),
('sport', 3, 'Quel pays a remporté le premier Championnat d\'Europe de football, en 1960 ?', "L'URSS", ['La Yougoslavie', "L'Espagne", 'La France']),
]

out = []
for i, (cat, d, q, a, bad) in enumerate(Q):
    assert len(bad) == 3 and a not in bad, q
    out.append({'id': 'x%03d' % i, 'cat': cat, 'src': 'maison', 'd': d, 'q': q, 'a': a, 'bad': bad})
json.dump(out, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz-extra.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=0)
from collections import Counter
print(len(out), dict(Counter(q['cat'] for q in out)))
